//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by commonres.rc
//

#define IDD_ABOUTBOX                    0x6F00
#define IDS_ABOUTBOX                    0x6F01
#define IDD_INETDOWNLOAD_DIALOG         0x6F02
#define IDS_HTTPDOWNLOAD_FILESTATUS     0x6F02
#define IDS_HTTPDOWNLOAD_CONNECTED      0x6F03
#define IDS_HTTPDOWNLOAD_RESOLVING_NAME 0x6F04
#define IDS_HTTPDOWNLOAD_RESOLVED_NAME  0x6F05
#define IDS_HTTPDOWNLOAD_CONNECTING		0x6F06
#define IDS_HTTPDOWNLOAD_REDIRECTING    0x6F07
#define IDS_HTTPDOWNLOAD_GETTING_FILE_INFORMATION 0x6F08
#define IDS_HTTPDOWNLOAD_FAIL_PARSE_ERROR 0x6F09
#define IDS_HTTPDOWNLOAD_GENERIC_ERROR  0x6F10
#define IDS_HTTPDOWNLOAD_FAIL_CONNECT_SERVER 0x6F11
#define IDS_HTTPDOWNLOAD_INVALID_SERVER_RESPONSE 0x6F12
#define IDS_HTTPDOWNLOAD_INVALID_HTTP_RESPONSE 0x6F13
#define IDS_HTTPDOWNLOAD_ERROR_READFILE 0x6F14
#define IDS_HTTPDOWNLOAD_PERCENTAGE     0x6F15
#define IDS_HTTPDOWNLOAD_RETREIVEING_FILE 0x6F16
#define IDS_HTTPDOWNLOAD_OF             0x6F17
#define IDS_HTTPDOWNLOAD_SECONDS        0x6F18
#define IDS_HTTPDOWNLOAD_MINUTES        0x6F19
#define IDS_HTTPDOWNLOAD_MINUTES_AND_SECONDS 0x6F20
#define IDS_HTTPDOWNLOAD_BYTES          0x6F21
#define IDR_MAINFRAME                   0x6F22
#define IDS_HTTPDOWNLOAD_KILOBYTES      0x6F23
#define IDD_HTTPDOWNLOAD                0x6F24
#define IDS_HTTPDOWNLOAD_MEGABYTES      0x6F25
#define IDR_HTTPDOWNLOAD_ANIMATION      0x6F26
#define IDS_HTTPDOWNLOAD_TIMELEFT       0x6F27
#define IDS_HTTPDOWNLOAD_BYTESPERSECOND 0x6F28
#define IDS_HTTPDOWNLOAD_KILOBYTESPERSECOND 0x6F29
#define IDS_HTTPDOWNLOAD_OK_TO_OVERWRITE 0x6F30
#define IDS_HTTPDOWNLOAD_FAIL_FILE_OPEN 0x6F31
#define IDS_HTTPDOWNLOAD_ABORTING_TRANSFER 0x6F32
#define IDC_ANIMATE1                    0x6F33
#define IDC_STATUS                      0x6F34
#define IDC_FILESTATUS                  0x6F35
#define IDC_PROGRESS1                   0x6F36
#define IDC_TIMELEFT                    0x6F37
#define IDC_TRANSFER_RATE               0x6F38
#define IDC_BUTTON1                     0x6F39
#define IDC_DOWNLOAD                    0x6F40
#define IDC_URL                         0x6F41
#define IDC_FILE                        0x6F42
#define IDC_USER                        0x6F43
#define IDC_PASSWORD                    0x6F44

// 新对象的下一组默认值
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	101
#define _APS_NEXT_COMMAND_VALUE		40001
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#endif
#endif
